name: Build Server & Monitor & Player

on: [push]

jobs:
  
  build-Agent-Lib:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install Dependency
      run: sudo apt-get update && sudo apt-get install -y g++ build-essential libboost-all-dev qt4-dev-tools libaudio-dev libgtk-3-dev libxt-dev bison flex
    - name: Build
      run: ./makeFirstTime.sh
      working-directory: ./player
    - name: Binary
      run: ./makeBin.sh
      working-directory: ./player
    - name: Archive Binary
      uses: actions/upload-artifact@v1
      with:
        name: Player Binary
        path: player/Bin/Binary.tar.gz
  
  build-server:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v2
    - name: install Dependency
      run: sudo apt-get update && sudo apt-get install -y g++ build-essential libboost-all-dev qt4-dev-tools libaudio-dev libgtk-3-dev libxt-dev bison flex
    - name: Build
      run: cd ./server && ./buildServer.sh
    - name: Archive Binary
      uses: actions/upload-artifact@v1
      with:
        name: Server Binary
        path: server/Bin/ServerBin.tar.gz